### ISSUE TITLE
Difference between releases on kristaps.bsd.lv and GitHub?

### ISSUE THREAD

**Issue by tfaughnan** [kristapsdz/kcgi#101]
What are the differences between releases from https://kristaps.bsd.lv/kcgi/snapshots/ and from https://github.com/kristapsdz/kcgi/tags ? They have different files/structure, and therefore different checksums... should I prefer one over the other?

**Comment by kristapsdz** [comment]
The kristaps.bsd.lv snapshots are canonical release snapshots containing only files required for building, with the hashes verified by me.  The GitHub download is (I think?) the full source tree as auto-generated by GitHub.  So some things will be different (e.g., *.gitignore*, etc.).  I wouldn't trust what's put out by GitHub.
