### ISSUE TITLE
Self-fulfill deffinition/header requriements

### ISSUE THREAD

**Issue by MaurolepisDreki** [kristapsdz/kcgi#102]
When using this tool, one should not have to go around the world to satisfy all the header requirements of your code; in your example, you pre-include <sys/types.h>, <stdarg.h>, <stddef.h>, and <stdint.h> to fulfill the definitions used by your own header <kcgi.h> rather than to fulfill the definition requirements of the end-program: these belong (possibly along with some processor code for C/C++ interoperability) at the top of <kcgi.h> rather than as a constant part of the user's code because *you* use them as opposed to *the end user* using them.

**Comment by kristapsdz** [comment]
Eh.

**Comment by MaurolepisDreki** [comment]
Because you closed this without fixing your problem, I'm going to build my own Fast CGI Application Interface instead of using yours.  However, because I'm a nice guy, I've attached the 12 page error log your code produces due to the issue.

Have a nice day!
[err.log](https://github.com/kristapsdz/kcgi/files/9735902/err.log)
