### ISSUE TITLE
No interface to `sock_ctl` on fcgi struct

### ISSUE THREAD

**Issue by nekobbbbbbit** [kristapsdz/kcgi#105]
Hi! I'm writing an application that uses regular FCGI libs, but I decided to give this one a look, and I noticed a design flaw for a feature I needed.

In my application, I poll a curl socket and FCGIapp socket, so I may use an Asynchronous design. With this library, this isn't possible since the kfcgi struct's implementation isn't exposed.

(more over, why isn't this typedef'd if you didn't plan to expose the API, and wanted to treat it as a regular type? Struct at least confirms that I could get at the data)

**Comment by kristapsdz** [comment]
The struct in the kcgi.h file are forward declarations: the API only uses pointers.  And as a matter of style, I don't use typedefs on structs.

You do raise a good point, though: internally, the `khttp_fcgi_parse` function just calls `fcgi_waitread` on the `sock_ctl` value, so it should be possible to to integrate this into an existing polling loop.  I'll add a function to grab this value and will close this issue when it's done.

**Comment by swagtoy** [comment]
Was bored and found this issue again and wanted to say thank you :)

When I get a chance I will maybe refactor my program to use kcgi... but, man, C for a webapp was very fun but nothing i ever want to do again
