### ISSUE TITLE
Enable the Wiki for the project

### ISSUE THREAD

**Issue by aggsol** [kristapsdz/kcgi#15]
People might run into issues and their fixes could be collected in the wiki. I am trying to build on Linux (Ubuntu 16.04) and `make regress` also need `libcurl3-dev` and `libbsd-dev` but the Makefile is not linking again `libbsd`. Having some place to look might help.

**Comment by kristapsdz** [comment]
Thanks --- I've added these requirements to the main project page, [index.xml](index.html), and have the [GNUmakefile](GNUmakefile) do better in detecting the appropriate headers on Linux.  (These will all appear in the next release.)  I don't think the wiki page should be used, however: it balkanises the documentation.  But there should probably be a section for downstream implementations.
