### ISSUE TITLE
extra line-break in headers

### ISSUE THREAD

**Issue by cornett** [kristapsdz/kcgi#2]
I'm seeing some strange behavior from the simple program below:

```
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include <kcgi.h>

int
main(void)
{
        struct kreq      r;
        struct kfcgi    *fcgi;

        if (khttp_fcgi_init(&fcgi, NULL, 0, NULL, 0, 0) != KCGI_OK)
                return 1;

        for (;;) {

                if (khttp_fcgi_parse(fcgi, &r) != KCGI_OK) {
                        khttp_free(&r);
                        break;
                }

                khttp_head(&r, kresps[KRESP_STATUS], "%s", khttps[KHTTP_200]);
                khttp_head(&r, kresps[KRESP_CONTENT_TYPE], "%s", kmimetypes[r.mime]);
                khttp_body(&r);

                khttp_puts(&r, "test\n");
                khttp_free(&r);
        }

        khttp_fcgi_free(fcgi);

        return 0;
}
```

This program produces the following http response when run on openbsd-current:

```
$ curl -i http://my.host/x
HTTP/1.1 200 OK
Connection: keep-alive
Date: Fri, 08 Apr 2016 15:38:14 GMT
Server: OpenBSD httpd
Transfer-Encoding: chunked

Status: 200 OK
Content-Type: text/html

test
$
```

There is a spurious line break before the Status header. 

I'm still working on debugging this, but so far I'm not even sure whether the problem is in kfcgi or in httpd.  Any suggestions would be appreciated.  Thanks!

**Comment by cornett** [comment]
https://marc.info/?l=openbsd-tech&m=144571751203238&w=2

**Comment by kristapsdz** [comment]
I can verify that this mentioned behaviour is still in effect as of the current [server_fcgi.c](https://github.com/reyk/httpd/blob/master/httpd/server_fcgi.c).  Right now, kcgi won't buffer its headers (as it does body content, assuming one doesn't disable buffering), so it will break these up into different STDOUT records--that would trigger the same problem.  Can you confirm that this error doesn't occur on other web servers?  Meanwhile, I'll have khttp_head buffer its output too: it wasn't doing so in the interests of simplicity.  This will work around the problem, but work around it very bluntly (til the buffer is saturated).  Again, if you can verify the problem, please ping @reyk.

**Comment by cornett** [comment]
I tested the program above yesterday with nginx on linux.   It worked fine.

**Comment by kristapsdz** [comment]
I just pushed a change to the repository that fixes this for a recent OpenBSD snapshot's httpd.  Does it work for you?  If so, I'll document it properly and merge it into the next version.

**Comment by cornett** [comment]
Indeed it does.   Thanks !
