### ISSUE TITLE
Documentation Bug? kjson_close()

### ISSUE THREAD

**Issue by protoCall7** [kristapsdz/kcgi#20]
Hello!

While adding error handling to a json sender, I noticed that sometimes kjson_close returns 0 on seemingly non-error states. After reading the code, it appears that kjson_close will return 1 if there were unclosed arrays, objects, or strings on the json stack, however if everything has been closed already, then the stack length is 0, and kjson_close() returns 0.

The documentation would lead developers to believe that 0 is an error state for all of the kcgijson functions that return an int, however this appears to not be the case for kjson_close.

Can you confirm that a 0 does not necessarily imply an error with this function?

**Comment by kristapsdz** [comment]
I can confirm this: the function will return non-zero if there are open scopes, zero if there are no open scopes.  So effectively zero is a "good return".  I'll fix the documentation---thanks!

**Comment by kristapsdz** [comment]
I've now clarified the return values.  Please re-open if you'd like more information---thanks again!
