### ISSUE TITLE
Forward reference to enum type

### ISSUE THREAD

**Issue by sirjorj** [kristapsdz/kcgi#28]
I have been working on a cgi application (https://github.com/sirjorj/xwingcgi) using kcgi and running it on a local openbsd machine.  It is essentially a web interface to a c++library that contains the data for a tabletop game.  I am not a web dev and was kind of intrigued bu the BCHS idea so I gave it a try.

Anyway, tonight I decided to get that project to build in linux.  After building and installing kcgi, I tried to build my project and got this error"

`/usr/local/include/kcgi.h:486:14: error: ISO C++ forbids forward references to 'enum' types`

I thought that was weird and compared that kcgi.h with the one on my openbsd machine and saw they were different.  I then updated the package on my openbsd machine (0.10.0 -> 0.10.1) and now I have the same build error on the openbsd machine!

Is this a regression in kcgi or am I using it wrong?

**Comment by kristapsdz** [comment]
Are you compiling with a C++ compiler?

**Comment by kristapsdz** [comment]
Try moving the line at 486 (the typedef) to below the enum, at the new line 507.  I'll try to test out a similar situation a bit later.

**Comment by sirjorj** [comment]
Yes, I am including it in a c++ project.

**Comment by sirjorj** [comment]
Had to move one other thing.

`
enum    kcgi_err {
        KCGI_OK = 0,
        /* ENOMEM (fork, malloc, etc.). */
        KCGI_ENOMEM,
        /* FastCGI request to exit. */
        KCGI_HUP,
        /* ENFILE or EMFILE (fd ops). */
        KCGI_ENFILE,
        /* EAGAIN (fork). */
        KCGI_EAGAIN,
        /* Internal system error (malformed data). */
        KCGI_FORM,
        /* Opaque operating-system error. */
        KCGI_SYSTEM
};

typedef enum kcgi_err (*ktemplate_writef)(const char *, size_t, void *);

struct  ktemplatex {
        ktemplate_writef         writer;
        int                     (*fbk)(const char *, size_t, void *);
};

__BEGIN_DECLS
`

This works in openbsd and probably linux (i say probably as there are other build errors but I'm pretty sure it is in my code.)
Thanks for the quick response!

**Comment by kristapsdz** [comment]
Great!  I'd never tried to use kcgi for a C++ application.  If you have time, I'd love to have a small tutorial on a "hello, world" C++ application using kcgi.  Just sayin... :)

**Comment by kristapsdz** [comment]
(I've now added one that will appear in the next version---if you have any input or suggestions, let me know!  It's tutorial5.xml.)
