### ISSUE TITLE
dead link to libcurl(3) on the site https://kristaps.bsd.lv/kcgi/kcgiregress.3.html

### ISSUE THREAD

**Issue by cyball** [kristapsdz/kcgi#31]
hey,

on the site https://kristaps.bsd.lv/kcgi/kcgiregress.3.html i found the link to libcurl(3) to be a dead link.
I am not very familiar with sblg, so i do not know for now how to fix it.

**Comment by kristapsdz** [comment]
That's actually in the mandoc(1) invocation in the GNUmakefile.  I've just removed the linking.  (The issue is a well-known mandoc -Thtml one: how does one know which of the links are reachable?  I know that Ingo would be happen with somebody hacking on an elegant solution!)  Thanks for the note!

**Comment by cyball** [comment]
once the site is deployed we can use a crawler(curl client) to get the site, and check something(title tag) on the site which does not change very often with a html parser, because sometimes a 200 response is not totally enough to be tested, so we can discover dead links
