### ISSUE TITLE
openbsd package

### ISSUE THREAD

**Issue by arimnus** [kristapsdz/kcgi#36]
I installed kcgi using pkg_add kcgi

Attempting to compile a test program with:
cc -static -g -w -Wall -o env.cgi env.c -lkcgi

I get a fatal error that kcgi.h cannot be found.

**Comment by jturner** [comment]
That's because OpenBSD packages install to /usr/local so you need to add `-L/usr/local/lib -I/usr/local/include`

**Comment by kristapsdz** [comment]
Yap  I don't mention **-I** and **-L** for individual operating systems because it depends on the system.
