### ISSUE TITLE
[Help wanted] FastCGI with kfcgi on macOS

### ISSUE THREAD

**Issue by sunqingyao** [kristapsdz/kcgi#40]
I need some help using FastCGI with `kfcgi` on macOS. By now I've built the executable, but I have no idea how to configure the server.

Actually I don't even know which server I'm using! macOS ships with a built-in server, but I'm not sure whether it's Apache or httpd, since both names seem to refer to the same thing.

```
~|⇒ apachectl -v
Server version: Apache/2.4.33 (Unix)
Server built:   Apr  3 2018 18:00:56
~|⇒ httpd -v
Server version: Apache/2.4.33 (Unix)
Server built:   Apr  3 2018 18:00:56
```

Anyway, I followed your [tutorial](https://kristaps.bsd.lv/kcgi/tutorial2.html) on working with httpd, but the server complains about a syntax error when I added the `server "me.local"` command into the configuration file [`/etc/apache2/httpd.conf`](https://github.com/kristapsdz/kcgi/files/2096950/httpd.conf.txt).

```
~|⇒ apachectl -t
AH00526: Syntax error on line 564 of /private/etc/apache2/httpd.conf:
Invalid command 'server', perhaps misspelled or defined by a module not included in the server configuration
```

I tried consulting the document but was soon overwhelmed by the huge amount of info: which module should I use, `mod_fastcgi`, `mod_fcgid`, or `mod_proxy_fcgi`? It would be great if you could provide an example, since most people don't have a machine running OpenBSD by their hand (remote servers are an option, but the connections are usually quite slow!)

**Comment by kristapsdz** [comment]
The tutorial mentioned is for OpenBSD's httpd.  I don't have any information on Mac OS X's Apache.  You might want to start by searching for running CGI scripts on Mac OS X, then FastCGI---which will be much more complicated.  kcgi's FastCGI scripts should work with kfcgi or the default Apache runner.

**Comment by sunqingyao** [comment]
I've managed to use this library with CGI on macOS, which is quite straightforward with your detailed tutorial, but working with FastCGI is indeed much harder!

I'll update this thread if I can get it to work.

**Comment by kristapsdz** [comment]
Great job!  I don't think it's worth digging around on this more: obviously there are some show-stopping bugs in Mac OS X.  Thank you so much for spending the time to uncover these!   I'll definitely take Apple off the list of supported systems.

**Comment by sunqingyao** [comment]
No problem, and you've also done a great job!

While it's regrettable to hear that you're going to drop support for macOS, I would say you've made a sensible decision, for it really doesn't qualify for a web server, at least not in the near future.

**Comment by kristapsdz** [comment]
I'll leave support enabled in case it's fixed, but just put up a PSA on the kcgi site that it might crash and shouldn't be trusted.  You can always try basic CGI scripts---but first see if something like the abort test case, where a validator abort()s, crashes the system as it did in the regression suite; and if it does, just... make sure your systems never abort.  :(  Either way, you get full credit for this discovery.  Thank you so much for your research!

As for FastCGI, variable mode (**-r**) might make a difference, but I doubt it.  My uninformed guess is that Mac pukes because of something regarding socketpair IPC.

**Comment by sunqingyao** [comment]
You're welcome :)

Just tried variable mode, and it works on my system!!! You may want to include this piece of information into the PSA.

```
~|⇒ sudo kfcgi -r -p / -U `whoami` -u `whoami` -- /var/www/fastcgi-minimal
Password:
~|⇒ nginx
~|⇒ curl -i localhost:8080
HTTP/1.1 200 OK
Server: nginx/1.15.0
Date: Thu, 14 Jun 2018 16:55:18 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

Hello, world!
```

**Comment by kristapsdz** [comment]
The `--` indicates an end to optional arguments. See [getopt(1)](https://man.openbsd.org/getopt) for details.  Thank you again!
