### ISSUE TITLE
Nim bindings

### ISSUE THREAD

**Issue by zacharycarter** [kristapsdz/kcgi#43]
Just put these together really quickly to allow me to experiment with some of the ideas from BCHS but using Nim instead of C. They compile on OSX, will try on OBSD later today - https://github.com/zacharycarter/kcgi.nim

**Comment by zacharycarter** [comment]
They compile fine on OpenBSD with the devel branch of Nim.

**Comment by kristapsdz** [comment]
@zacharycarter , I'm not sure how you'd like this to be included in kcgi.  Do you think a link from the main page suffices?

**Comment by zacharycarter** [comment]
Sorry - I didn't mean to insinuate that you needed to do anything with it - I was just playing around with Nim, BCHS, kcgi, etc... and thought it would be a fun experiment. I didn't get very far unfortunately though :( I really do like what you're doing with BCHS though! Keep up the great work!
