### ISSUE TITLE
Which process to attach when debugging?

### ISSUE THREAD

**Issue by nalzok** [kristapsdz/kcgi#47]
I would like to debug my kcgi application with a debugger like `gdb` or `lldb`. Since I'm not running the application directly but instead serving it with `kfcgi`, I had a really hard time struggling to attach it to a debugger.

After some research, I discovered a feature named [attach to local process](https://www.jetbrains.com/help/clion/attaching-to-local-process.html) supported by my IDE, CLion, and it seems promising. However, I still have no idea which local process to attach, because there are so many!

![screen shot 2018-07-15 at 10 27 18](https://user-images.githubusercontent.com/13443062/42729895-bf0c3848-8819-11e8-90b5-a4ccb77bba8a.png)

Do you think attaching to a local process is a feasible way of making a debugger to work with my kcgi application? If not, would [remote debugging](http://lldb.llvm.org/remote.html) be a better approach?

For your reference, here is the script I'm using to automate deployment in my dev environment. Note that I'm using the variable mode (`-r`) due to a [macOS bug](https://github.com/kristapsdz/kcgi/issues/40).

```
#!/usr/bin/env bash

mkdir -p /usr/local/var/www/fcgi-bin /usr/local/var/www/run
install -m 0555 cmake-build-debug/kernod /usr/local/var/www/fcgi-bin
echo $LOGIN_PASSWD | sudo -S : 2>/dev/null  # do nothing
sudo /usr/local/sbin/kfcgi -d -r \
    -s /usr/local/var/www/run/httpd.sock \
    -p /usr/local/var/www \
    -u `whoami` -U `whoami` -- /fcgi-bin/kernod

```

**Comment by kristapsdz** [comment]
I'm closing out this comment as it looks long dead.  (I had no advise: I build with debugging, and if systems crash, I just look at the coredumps.)
