### ISSUE TITLE
oconfigure does not work for cross-compile.

### ISSUE THREAD

**Issue by sammyj85** [kristapsdz/kcgi#52]
The configure script attempts to execute the compiled tests, which fail if configuring for a cross-compiled situation.

Upgrade oconfigure to not run the tests, since there is apparently nothing to be gained from running them:
https://github.com/kristapsdz/oconfigure/commit/5e57079992f6d9a0a19945e277ae8dbdb19c1121

**Comment by kristapsdz** [comment]
This is fixed with the upgraded oconfigure.  Thanks!
