### ISSUE TITLE
JSON Control Character Encoding breaks UTF-8 strings on architectures with signed char

### ISSUE THREAD

**Issue by nonrecursive** [kristapsdz/kcgi#56]
My application uses kcgijson to send UTF-8-encoded strings.

When I send a string like "für", the browser receives "f\\uFFFF\\uFFFFr" ("ü" is actually 0xC3 0xBC).

I suspect the bug is in the control character escaping:
```
    /* Encode control characters. */
    if (cp[i] <= 0x1f) {
      snprintf(enc, sizeof(enc), "\\u%.4X", cp[i]);
      /* note: sizeof(enc) == 7, therefore %.4X can only print four bytes at max */
      e = kcgi_writer_puts(r->arg, enc);
      if (KCGI_OK != e)
        return (e);
      continue;
    }
```
The problem here is that 0xC3 is (given that, on your architecture, `char` is `signed`) negative and is therefore falsely recognized as a control character. It is then expanded to an int and the upper two bytes of that int are printed (which are FFFF, as that `int` has been created from a negative `char`).

The function works correctly if a cast to `unsigned char` is added:
```
static enum kcgi_err kjson_write(struct kjsonreq *r, const char *c
                                                             /* renamed parameter, for the sake of this example */,
                                                    size_t sz, int quot) {
  enum kcgi_err e;
  char enc[7];
  size_t i;
  
  const unsigned char *cp;
  cp = (const unsigned char*)c;
```

**Comment by kristapsdz** [comment]
This was a really great find, thank you so much!  I've also added a regression test to make sure this kind of thing doesn't creepy back in.
