### ISSUE TITLE
How do I emit css for the STYLE tag without encoding the '>' character

### ISSUE THREAD

**Issue by sirjorj** [kristapsdz/kcgi#67]
I have been using this library for over a year now for a hobby project and I have been very happy with it.

Today I am refactoring my CSS handling and hit a snag - I am trying to put all my CSS in the STYLE tag within the HEAD tag.  I just learned about Child Combinators but when I try to use them, the '>' character becomes '&#x3e;'.  I am using khtml_puts() to output the css string after the STYLE tag.  Is there a way to emit text without it getting html encoded?

**Comment by kristapsdz** [comment]
You can directly use the khttp_write family.  khtml_write won't output CSS because it's not... HTML. :)

**Comment by sirjorj** [comment]
Ahh... that one bypasses the html encoding.  Makes sense.  Thanks!
