### ISSUE TITLE
macos make error like this 

### ISSUE THREAD

**Issue by chujiangke** [kristapsdz/kcgi#68]
xiaoleidembp:kcgi richard$ ./configure 
config.log: writing...
configure.local: no (fully automatic configuration)
arc4random: yes 
b64_ntop: yes (with -lresolv)
capsicum: no
err: yes 
explicit_bzero: no
getprogname: yes 
INFTIM: no
md5: no
memmem: yes 
memrchr: no
memset_s: yes 
PATH_MAX: yes 
pledge: no
program_invocation_short_name: no
reallocarray: no
recallocarray: no
sandbox_init: yes 
seccomp-filter: no
SOCK_NONBLOCK: no
strlcat: yes 
strlcpy: yes 
strndup: yes 
strnlen: yes 
strtonum: no
sys_queue: yes 
systrace: no
unveil: no
zlib: yes 
__progname: yes 
config.h: written
Makefile.configure: written
xiaoleidembp:kcgi richard$ make
Makefile:309: *** missing separator.  Stop.
xiaoleidembp:kcgi richard$

**Comment by chujiangke** [comment]
Makefile 309 below

                                                                                                                                                        
for BIN in $(REGRESS)                                                                                                                                   
    $(BIN): $(BIN).c                                                                                                                                    
        $(CC) $(CFLAGS) `curl-config --cflags` -o $@ $(BIN).c \                                                                                         
            regress/regress.o libkcgiregress.a libkcgijson.a \                                                                                          
            libkcgi.a `curl-config --libs` -lz $(LDADD)                                                                                                 
endfor

**Comment by kristapsdz** [comment]
You need bsdmake (from, e.g., homebrew or macports or whatever is popular these days).  Mac uses gmake by default.

Reason behind using BSD vs GNU make is that there's enough to build that I use some simple looping and this was beyond the purview of POSIX make, so I had to make a choice.
