### ISSUE TITLE
newer libcurl versions brings up issues with HTTP-Version not being correctly handled

### ISSUE THREAD

**Issue by xse** [kristapsdz/kcgi#72]
### **This first post can be entirely skipped i leave it there for context.**
libcurl now requires explicitly opting in to HTTP/0.9 to get the fcgi regress tests working.
This post is kinda long 'cause i edited it many times while figuring out the issue. 

Hello,

Both systems were tests are failing are archlinux.
I've noted some similarities with #39 
`bmake regress` fails on test-fcgi-bigfile.

"By return value" the following tests are failing:

- test-fcgi-bigfile
- test-fcgi-file-get
- test-fcgi-header
- test-fcgi-header-bad
- test-fcgi-path-check
- test-fcgi-path-check
- test-fcgi-ping
- test-fcgi-ping-double
- test-fcgi-upload
- test-upload (the only one that's not fcgi)

**test-abort-validator** and **test-fcgi-abort-validator** are both generating a coredump.

### On armv6, note about the sandbox

Platform: `Linux rpi 4.19.79-1-ARCH #1 SMP PREEMPT Sat Oct 12 17:02:53 UTC 2019 armv6l GNU/Linux`

Looking into the sandbox stuff, `-DSANDBOX_SECCOMP_DEBUG` did not output anything at all but for the two validator tests strace shown two syscalls that were apparently blocked by it:
gettid:
```
[pid 23412] gettid( <unfinished ...>
[pid 23412] --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x76d0931c, si_syscall=__NR_gettid, si_arch=AUDIT_ARCH_ARM} ---
```
and tgkill:
```
[pid 24039] tgkill(24039, 24039, SIGABRT <unfinished ...>
[pid 24039] --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x76cf8330, si_syscall=__NR_tgkill, si_arch=AUDIT_ARCH_ARM} ---
```

After adding those two to the preauth_ctrl and preauth_work arrays in sandbox-seccomp-filter.c, [the test now executes gettid and tgkill, then it calls rt_sigprocmask which was already authorized and it then receive a SIGABRT](https://gist.github.com/xse/6b689dc79620b474a3bf1d2f1ce9e1f6#file-4-L1964). (Before those changes it was a SIGSYS triggering the dump)
_That doesn't change much but i guess abort is intended while the seccomp block isn't._

To try and fix the fcgi tests, i've also tried building everything with -fsigned-char since i'm getting a signedness warning when building on x86, with no success.

### On x86_64, same fcgi tests are failing. Only noted on arch linux

Platform: `Linux krkrkr.org 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux`

The same exact tests are returning != 0.

I did not notice any errors on debian, might be archlinux related. I just tested versions as far back as 0_10_3 which was working well back then, make regress failing there too.

EDIT: aight just verified on a fresh x86 debian, no issues here. Seems arch related.

### 19/10/18 update

Noted a sandbox message on arch, only saw that once so far tho so to me it seems totally unrelated:
```
ssh_sandbox_violation_control: unexpected system call (control) (arch:0xc000003e,syscall:219 @ 0x7f9245ad79b7)
ssh_sandbox_violation_worker: unexpected system call (worker) (arch:0xc000003e,syscall:219 @ 0x7f9245ad79b7)

```

On debian, this test executes and exits, on arch, it stays open in the background expecting something
Really does not look like to be a sandbox issue to me the logs don't show anything related to what was there for gettid and tgkill on arm.
Few strace logs debian vs arch [are available here](https://gist.github.com/xse).

**This looks to me like a socket issue.**

- The debian  fcgi bigfile test launchs several sendto(), then gets a bunch of recvfrom()
- The arch one do that too, but it only gets a single recvfrom() before getting a `write: Connection reset by peer`

### libcurl

Trying to understand that, i've modified the fcgi-bigfile test, adding:
`curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);`
The outputs now differs quite a bit from [arch](https://gist.github.com/xse/34183f7c9fe196ba7cd6095f1f837ad7) & [debian](https://gist.github.com/xse/0e9777a519c1776cdf1bd880833a75b1).

The main issue seems to be: ([see also](https://github.com/curl/curl/issues/2873))
```
* Received HTTP/0.9 when not allowed

* Closing connection 0
write: Connection reset by peer
```

And indeed adding : `curl_easy_setopt(curl, CURLOPT_HTTP09_ALLOWED, 1L);` to the fcgi bigfile test makes it pass on archlinux.

Have a good day!

**Comment by xse** [comment]
Alright changes in #73 fix the libcurl issue.

**Comment by kristapsdz** [comment]
This has been fixed and will be in the next version.  Thank you!
