### ISSUE TITLE
khttp_printf / khttp_vprintf

### ISSUE THREAD

**Issue by markand** [kristapsdz/kcgi#76]
Hi,

First, thank you for this awesome library. I enjoy it a lot.

I just realized there is no `khttp_(v)printf` functions to format using printf(3) like style. If you mind, I'd like to add it unless you already had this in some TODO list.

**Comment by kristapsdz** [comment]
Go write ahead!  You'll probably end up just wrapping asprintf and passing that.  Please be sure to add the manpage and a regression test for it, either way!

**Comment by kristapsdz** [comment]
`khttp_printf` has been added along with manpage and regression tests.
