### ISSUE TITLE
What does the integer input in sample.c ?

### ISSUE THREAD

**Issue by echkourine25** [kristapsdz/kcgi#80]
I enter a number and send form but it does nothing.
I do not understand these lines in sendindex() of sample.c
`	cp = NULL == req->fieldmap[KEY_INTEGER] ?
		"" : req->fieldmap[KEY_INTEGER]->val;
	kasprintf(&page, "%s/%s", req->pname, pages[PAGE_INDEX]);`

**Comment by kristapsdz** [comment]
The first assigns the value of `KEY_INTEGER` ("integer") to `cp` or the empty string if no value is given.  The second formats the CGI script name and the index page as a path.
