### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by echkourine25** [kristapsdz/kcgi#81]
Have a look here : [stackoverflow](https://stackoverflow.com/questions/60480512/had-a-segmentation-at-the-end-of-execution-of-the-program-dunno-what-im-doing-w)

Thank you.

**Comment by kristapsdz** [comment]
Buddy this isn't an appropriate place for C questions, so I'm closing the issue.  If you find something specifically in kcgi, then by all means ask.

However, when you post these questions whether here or on SO, you're not going to get valuable feedback unless you also provide a backtrace, versions of software (and how you acquired them), how you compiled, etc.  As for your code, I've found at least one problem in simply looking it over.  (Namely that you're passing to your callback a pointer to a pointer &req, but reading it back as a pointer alone.)  So I suggest spending some time with printfs and a debugger.
