### ISSUE TITLE
Fails To Build On Pinebook Pro (Manjaro, ARM64)

### ISSUE THREAD

**Issue by tekktonic** [kristapsdz/kcgi#96]
Configure works fine, but it hits compiler errors on the actual make. Happens with both the latest release and HEAD. Kernel is 5.13.12-1-MANJARO-ARM. It fails to compile on both clang and gcc, but I've included the clang version since it's what would be used on BSDs and has better output.
[configure.log](https://github.com/kristapsdz/kcgi/files/7111802/configure.log)
[make.log](https://github.com/kristapsdz/kcgi/files/7111803/make.log)

**Comment by kristapsdz** [comment]
This should now be fixed, as I've disabled seccomp for Linux systems by default.  Sorry for the delay!

**Comment by tekktonic** [comment]
Just tested, compiles fine.

**Comment by kristapsdz** [comment]
Thanks for testing!  I'll be release imminently with this in it.
